version: '2'
services:
  web:
#   build: ./container/
    image: fireball8931/apache_php:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    restart: always

#networks: 
#  default: 
#    external:
#      name: nginx_proxy_manager_default 
