version: '2'
services:
  web:
     image: fireball8931/apache_php:latest
#    build: ./container/
#    ports:
#      - "8080:80"
    volumes:
      - ./www:/var/www/html
    restart: always

networks: 
  default: 
    external:
      name: nginx_proxy_manager_default 
