name: Build and Test Website

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Start webserver
      run: npx http-server www -p 8080 &

    - name: Test website
      run: |
        npm install -g crawl
        crawl http://localhost:8080 -r 1 -e -f